name: Publish to PyPI
run-name: ${{ github.actor }} is publishing to PyPI
on:
  workflow_dispatch:
jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment:  publish_to_pypi
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      # retrieve your distributions here
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip build
      - name: Build Source and Wheel Distributions
        run: python -m build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1